CC = gcc
CFLAGS = -Wall -Wextra -g
MKSTR = $(CC) $@.c -o bin/$@ $(CFLAGS)

all: ex_1 ex_3 ex_4 ex_5 ex_6 ex_7 ex_8 ex_9 ex_10 ex_11 ex_12 ex_13 ex_14 ex_15 ex_16 ex_17 stack ex_18 ex_19

ex_1:
	$(MKSTR)

ex_3:
	$(MKSTR)

ex_4:
	$(MKSTR)

ex_5:
	$(MKSTR)

ex_6:
	$(MKSTR)

ex_7:
	$(MKSTR)

ex_8:
	$(MKSTR)

ex_9:
	$(MKSTR)

ex_10:
	$(MKSTR)

ex_11:
	$(MKSTR)

ex_12:
	$(MKSTR)

ex_13:
	$(MKSTR)

ex_14:
	$(MKSTR)

ex_15:
	$(MKSTR)

ex_16:
	$(MKSTR)

ex_17:
	$(MKSTR)

stack:
	$(MKSTR)

ex_18:
	$(MKSTR)

ex_19:
	make -C ex_19/

clean:
	rm -f bin/*
